using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

public class New1 : MonoBehaviour
{
    // public CubeController cube;
    
    private void OnEnable()
    {
        VisualElement root = GetComponent<UIDocument>().rootVisualElement;

        Button buttonStart = root.Q<Button>("ButtonStart");
        Button buttonStop  = root.Q<Button>("ButtonStop ");
        Button buttonColor = root.Q<Button>("ButtonColor");

        // buttonStart.clicked += () => cube.StartRotate();
        // buttonStop.clicked += () => cube.StopRotate();
        // buttonColor.clicked += () => cube.ChangeColor();
    }
}


